name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Step 4: Build executable
      - name: Build executable
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            pyinstaller --onefile --add-data "wolf.ico;." --add-data "main.py;." --hidden-import="streamlit" --name "inkWise" launcher.py
          else
            pyinstaller --onefile --add-data "wolf.ico:." --add-data "main.py:." --hidden-import="streamlit" --name "inkWise" launcher.py
          fi
        shell: bash

      # Step 5: Debug build output
      - name: Debug build output
        run: ls -R dist

      # Step 6: Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: inkWise-${{ matrix.os }}
          path: dist/inkWise*
          if-no-files-found: warn

  release:
    # Release job depends on build job
    needs: build
    runs-on: ubuntu-latest

    # Ensure compatibility across OS artifacts
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Download artifacts
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: inkWise-${{ matrix.os }}
          path: dist/

      # Step 3: Debug downloaded artifacts
      - name: Debug downloaded artifacts
        run: ls -R dist/

      # Step 4: Create Release
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/**/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
